# Generated by Django 5.0.6 on 2025-11-28 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_banner_homeconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeconfig',
            name='subtitulo',
            field=models.TextField(blank=True, default='Rutinas para cada tipo de piel'),
        ),
    ]
