# Generated by Django 5.0.6 on 2026-03-04 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_alter_homeconfig_subtitulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='texto',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='titulo',
        ),
    ]
