# Generated by Django 5.0.6 on 2025-09-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='home_banners/')),
                ('titulo', models.CharField(blank=True, max_length=120)),
                ('texto', models.CharField(blank=True, max_length=220)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='HomeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Descubre el mejor SkinCare coreano', max_length=120)),
                ('subtitulo', models.CharField(blank=True, default='Rutinas para cada tipo de piel', max_length=200)),
                ('mostrar_destacados', models.BooleanField(default=True)),
                ('cantidad_destacados', models.PositiveIntegerField(default=8)),
            ],
            options={
                'verbose_name': 'Configuración del Home',
                'verbose_name_plural': 'Configuración del Home',
            },
        ),
    ]
