"""
Django settings for core project.
Generated by 'django-admin startproject' using Django 5.0.6.
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url

# Directorio Base
BASE_DIR = Path(__file__).resolve().parent.parent

# Cargar variables de entorno (.env)
load_dotenv()

# --- CONFIGURACIÓN DE SEGURIDAD ---
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-n!^h1gl%_)^6i8$ji)$6&2^b_jfmr(y*t4()7e%(eljtnem+f4")

# En Render, DEBUG debe ser False para velocidad y seguridad
DEBUG = os.getenv("DEBUG", "False") == "True"

# Dominios permitidos (En Render usa el asterisco "*" o tu dominio exacto sin https://)
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost,*").split(",")

# --- DEFINICIÓN DE APLICACIONES ---
INSTALLED_APPS = [
    'cloudinary_storage',  # DEBE IR PRIMERO para capturar archivos media
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'cloudinary',          # Conexión con el servicio en la nube
    'catalogo',            # Tu aplicación de tienda
    'tailwind',            # Integración de Tailwind
    'theme',               # Tu tema de diseño
]

# --- MIDDLEWARE ---
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Para servir archivos estáticos (CSS/JS)
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

# --- PLANTILLAS (TEMPLATES) ---
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.cart_context', # Procesador del carrito
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# --- BASE DE DATOS (PostgreSQL en Render) ---
DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}

# --- VALIDACIÓN DE CONTRASEÑAS ---
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# --- INTERNACIONALIZACIÓN ---
LANGUAGE_CODE = 'es'
TIME_ZONE = 'America/Guayaquil'
USE_I18N = True
USE_TZ = True

# --- ARCHIVOS ESTÁTICOS (CSS, JS) ---
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

# Configuración WhiteNoise corregida para evitar errores de despliegue en Render
STATICFILES_STORAGE = "whitenoise.storage.StaticFilesStorage"
WHITENOISE_USE_FINDERS = True

# --- ARCHIVOS MEDIA (Imágenes en Cloudinary) ---
# Al configurar Cloudinary, las imágenes se guardarán permanentemente en la nube
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
}

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# --- OTRAS CONFIGURACIONES ---
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Tailwind settings
TAILWIND_APP_NAME = 'theme'
INTERNAL_IPS = ["127.0.0.1"]